version: "3.8"

services:
  webapp:
    container_name: sendgrid_fanout_www

    # Building our project image using the project Dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile

    # Running as "app" user
    user: app

    # Setting the working directory
    working_dir: /src/

    # Running the command which will render our application
    command: "hypnotoad -f server.pl"

    # Exposing the port
    ports:
      - ${BIND_ADDRESS}:8080

    environment:
      - DISABLE_TRACE_DIR=${DISABLE_TRACE_DIR}
      - AUTO_START_DIR=${AUTO_START_DIR}
      - ERROR_DIR=/data/error-dir
      - TRACE_DIR=/data/trace-dir
      - CONFIG_FILE=/src/config.json
      - MOJO_INACTIVITY_TIMEOUT=60
      - MOJO_KEEP_ALIVE_TIMEOUT=30
      - MOJO_HYPNOTOAD_WORKERS=1

    volumes:
      - ${ERROR_DIR}:/data/error-dir
      - ${TRACE_DIR}:/data/trace-dir
      - ${CONFIG_FILE}:/src/config.json
    logging:
      driver: "json-file"
      options:
        max-file: "${LOG_MAX_FILE}"
        max-size: "${LOG_MAX_SIZE}"


    restart: "unless-stopped"
